In [2]:
import pandas as pd

In [9]:
df = pd.read_csv('test_conv_level_complex.csv')
df

,conversation_num,speaker_nickname,timestamp,message
0,A,John,2020-04-20T18:27:20.125Z,"""I'm curious how do you all feel about using ..."
1,A,Mary,2020-04-20T18:27:40.125Z,"""I think flashcards are a great way to memori..."
2,A,John,2020-04-20T18:28:00.125Z,"""I agree I've found them to be really helpful."""
3,A,Jessica,2020-04-20T18:28:20.125Z,"""I'm not a big fan of flashcards I find them ..."
4,A,Mary,2020-04-20T18:28:40.125Z,"""I think it really depends on the individual ..."
5,A,John,2020-04-20T18:29:00.125Z,"""That's true I know some people who prefer to..."
6,A,Jessica,2020-04-20T18:29:20.125Z,"""I've heard of spaced repetition but I've nev..."
7,A,John,2020-04-20T18:29:40.125Z,"""It's a great way to improve your long-term m..."
8,A,Mary,2020-04-20T18:30:00.125Z,"""I'll have to give it a try."""
9,A,Jessica,2020-04-20T18:30:20.125Z,"""Do you have any tips for studying effectively?"""
10,A,John,2020-04-20T18:30:40.125Z,"""I find that studying in short bursts is more..."
11,A,Mary,2020-04-20T18:31:00.125Z,"""I agree it's also important to take breaks a..."
12,A,Jessica,2020-04-20T18:31:20.125Z,"""I'm always struggling to stay motivated any ..."
13,A,John,2020-04-20T18:31:40.125Z,"""I find it helpful to set realistic goals and..."
14,A,Mary,2020-04-20T18:32:00.125Z,"""It's also important to find a study buddy or..."
15,A,Jessica,2020-04-20T18:32:20.125Z,"""Thanks for the advice I'll definitely try it..."
16,B,A,2020-04-20T18:27:20.125Z,"""Hi everyone what are your favorite study hab..."
17,B,B,2020-04-20T18:27:40.956Z,"""I like to study in a quiet place where I can..."
18,B,C,2020-04-20T18:28:01.789Z,"""I prefer to study with a group of friends so..."
19,B,D,2020-04-20T18:28:23.621Z,"""I like to study by myself so I can go at my ..."
20,B,A,2020-04-20T18:28:45.452Z,"""I think it's important to find a study metho..."
21,B,B,2020-04-20T18:29:07.284Z,"""I agree."""
22,B,C,2020-04-20T18:29:29.116Z,"""I also think it's important to take breaks w..."
23,B,D,2020-04-20T18:29:50.947Z,"""Yes it's important to give your brain a chan..."
24,B,A,2020-04-20T18:30:12.778Z,"""I find that it's helpful to set a timer and ..."
25,B,B,2020-04-20T18:30:34.610Z,"""That's a good idea I'll try that."""
26,B,C,2020-04-20T18:30:56.441Z,"""I like to listen to music while I study it h..."
27,B,D,2020-04-20T18:31:18.273Z,"""I prefer to study in silence so I can focus ..."
28,B,A,2020-04-20T18:31:40.105Z,"""I find that it's helpful to create a study s..."
29,B,B,2020-04-20T18:32:01.936Z,"""I agree it's important to be consistent with..."
30,B,C,2020-04-20T18:32:23.768Z,"""I also think it's important to reward yourse..."
31,B,D,2020-04-20T18:32:45.599Z,"""Yes it's important to stay motivated while y..."
32,C,A,2020-04-20T18:27:20.125Z,"""I'm really struggling to stay focused when I..."
33,C,B,2020-04-20T18:27:32.456Z,"""I know what you mean. I have the same problem."""
34,C,C,2020-04-20T18:27:44.567Z,"""I've been trying to find a study method that..."
35,C,B,2020-04-20T18:29:22.456Z,"""I've found that it helps to break down my st..."
36,C,C,2020-04-20T18:29:44.567Z,"""That's a good idea. I'll try that."""
37,C,A,2020-04-20T18:29:52.456Z,"""I've also found that it helps to study in a ..."
38,C,D,2020-04-20T18:31:24.567Z,"""I agree. It's hard to concentrate when there..."
39,C,A,2020-04-20T19:31:32.456Z,"""Another thing that I've found helpful is to ..."
40,C,B,2020-04-20T19:31:34.567Z,"""That's a good idea. It helps me to stay on t..."
41,C,C,2020-04-20T19:33:22.456Z,"""I'm going to try that too."""
42,C,D,2020-04-20T19:33:24.567Z,"""I've also found that it helps to reward myse..."
43,C,A,2020-04-20T19:33:32.456Z,"""That's a good idea. It gives me something to..."
44,C,B,2020-04-20T19:33:44.567Z,"""I agree. It helps me to stay motivated."""
45,C,C,2020-04-20T20:35:32.456Z,"""I've found that it's also important to take ..."
46,C,D,2020-04-20T20:35:44.567Z,"""I agree. It helps me to stay focused and avo..."
47,C,A,2020-04-20T20:35:52.456Z,"""I've also found that it helps to study with ..."
48,C,B,2020-04-20T20:35:56.567Z,"""That's a good idea. It can help you to stay ..."

In [10]:
# add a column to the dataframe called feature and assign value of "team_burstiness" to every row
df['feature'] = 'team_burstiness'

In [12]:
# write the dataframe to a new csv file
df.to_csv('test_conv_level_complex.csv', index=False)

In [13]:
# parse file as txt and remove all quotes
with open('test_conv_level_complex.csv', 'r') as file:
    data = file.read()
    data = data.replace('"', '')

# write the data back to the file
with open('test_conv_level_complex.csv', 'w') as file:
    file.write(data)

In [69]:
df = pd.read_csv("../../output/conv/test_conv_level_conv_complex.csv")
df[['conversation_num', 'variance_in_DD']]

  conversation_num  variance_in_DD
0                A        0.023184
1                B        0.003812
2                C        0.000887
3                D        0.009075
4                E        0.022204
5                F        0.009982
6                G        0.065572
7                H        0.046539
8                I        0.023111

In [107]:
df = pd.read_csv('fflow.csv')
# df['feature'] = 'forward_flow'
# df['conversation_num'] = 'F'
# df['message'] = "Sports are a great way to stay active and healthy."
df['test_type'] = 'unit_eq'
df[['conversation_num', 'speaker_nickname', 'message', 'feature', 'test_type']].to_csv('fflow.csv', index=False)

In [100]:
df = pd.read_csv('../../output/chat/test_forward_flow_chat.csv')

def get_conversation_batches(dataframe, batch_size=3):
    # group by conversation_num and get the last row from the group
    last_rows = dataframe.groupby('conversation_num').tail(1)

    # get 3 row batches of these last rows
    batches = []
    rows = list(last_rows.iterrows())
    for i in range(0, len(rows), batch_size):
        batches.append(rows[i:i + batch_size])
    return batches

batches = get_conversation_batches(df, batch_size=3)
for batch in batches:
    print(batch[0][1]['forward_flow'])

0.9004621104890905

In [11]:
import pandas as pd
import datetime as dt

df = pd.read_csv('helper.csv')
df["timestamp"] = pd.to_datetime(df["timestamp"])
df["timestamp"] = df["timestamp"].apply(lambda x: x.timestamp())
# # convert time stamp to unix timestamp
# df["timestamp"] = df["timestamp"].astype(int) // 10**9
# df['conversation_num'] = 'X'
df['timestamp']

df.to_csv('helper.csv', index=False)

In [23]:
pd.to_datetime("2024-07-15T23:15:36.779590")

Timestamp('2024-07-15 23:15:36.779590')

In [21]:
df = pd.read_csv('helper.csv')
df["timestamp"] = df['timestamp'].apply(lambda x: dt.datetime.fromtimestamp(x))
df['timestamp']
# pd.to_datetime(df["timestamp"], unit='ms')

0   1969-12-31 19:00:20
1   1969-12-31 19:00:40
2   1969-12-31 19:01:00
3   1969-12-31 19:01:20
4   1969-12-31 19:01:40
Name: timestamp, dtype: datetime64[ns]

In [15]:
replacement_dict = {
    'A': 'V',
    'B': 'W',
    'C': 'X'
}

df = pd.read_csv('helper.csv')
# Add the conversation_num column and apply the replacement
df['conversation_num'] = df['conversation_num'].replace(replacement_dict)
df.to_csv('helper.csv', index=False)
# print(df)

In [61]:
df = pd.read_csv("../../output/chat/test_conv_level_chat_complex.csv")
df[0:60][['conversation_num', 'time_diff']]

   conversation_num       time_diff
0                 A             0.0
1                 A         0:00:20
2                 A         0:00:20
3                 A         0:00:20
4                 A         0:00:20
5                 A         0:00:20
6                 A         0:00:20
7                 A         0:00:20
8                 A         0:00:20
9                 A         0:00:20
10                A         0:00:20
11                A         0:00:20
12                A         0:00:20
13                A         0:00:20
14                A         0:00:20
15                A         0:00:20
16                B             0.0
17                B  0:00:20.831000
18                B  0:00:20.833000
19                B  0:00:21.832000
20                B  0:00:21.831000
21                B  0:00:21.832000
22                B  0:00:21.832000
23                B  0:00:21.831000
24                B  0:00:21.831000
25                B  0:00:21.832000
26                B  0:00:21.831000
27                B  0:00:21.832000
28                B  0:00:21.832000
29                B  0:00:21.831000
30                B  0:00:21.832000
31                B  0:00:21.831000
32                C             0.0
33                C  0:00:12.331000
34                C  0:00:12.111000
35                C  0:01:37.889000
36                C  0:00:22.111000
37                C  0:00:07.889000
38                C  0:01:32.111000
39                C  1:00:07.889000
40                C  0:00:02.111000
41                C  0:01:47.889000
42                C  0:00:02.111000
43                C  0:00:07.889000
44                C  0:00:12.111000
45                C  1:01:47.889000
46                C  0:00:12.111000
47                C  0:00:07.889000
48                C  0:00:04.111000
49                D             0.0
50                D             NaN
51                D             NaN
52                D             NaN
53                D             NaN
54                D             NaN
55                D             NaN
56                D             NaN
57                D             NaN
58                D             NaN
59                E             0.0

In [55]:
def coerce_to_date_or_number(value):
    """
    Helper function in which we check that the timestamp column contains either a datetime value or a number
    that can be interpreted as a time elapsed; otherwise, sets it equal to none.

    Args:
        value: The value to check; type can be anything
    Returns:
        Either the value itself (if it is a valid timestamp value) or None otherwise

    """
    try:
        pd.to_datetime(value)
        return value
    except (ValueError, TypeError):
        try:
            pd.to_numeric(value)
            return value
        except (ValueError, TypeError):
            print(f"Value {value} is not a valid timestamp or number.")
            return None
        
def time_string_to_float(time_str):
    # Split the time string into hours, minutes, and seconds.microseconds
    if (time_str == '0.0'):
        return 0
    time_parts = time_str.split(':')
    
    # Extract hours, minutes, and seconds.microseconds
    hours = int(time_parts[0])
    minutes = int(time_parts[1])
    seconds = float(time_parts[2])
    
    # Convert hours and minutes to seconds
    total_seconds = hours * 3600 + minutes * 60 + seconds
    
    return total_seconds

def burstiness(df, timediff):


    if timediff not in df.columns:
        return None 
   
    # Check for any NA values and drop them accordingly
    df[timediff] = df[timediff].apply(coerce_to_date_or_number)

    wait_times = (df[timediff].dropna()).apply(time_string_to_float)
    if len(wait_times) <= 1:
        return 0
    
    wait_times = wait_times[1:]

    # Compute coefficient of variation measure B (Goh & Barabasi 2008)
    standard_deviation = np.std(wait_times)
    mean = np.mean(wait_times)
    B = (standard_deviation - mean) / (standard_deviation + mean)
    return B

if "time_diff" not in df.columns:
    print(f"Temporal Features are nonexistent for this dataset.")

# Applies burstiness function to overall dataframe and then groups coefficient by conversation number
burst = df.groupby("conversation_num").apply(lambda x : burstiness(x, "time_diff")).reset_index().rename(columns={0: "team_burstiness"})
burst

  conversation_num  team_burstiness
0                A        -1.000000
1                B        -0.969164
2                C         0.426946
3                D         0.000000
4                E         0.000000
5                F         0.000000
6                G        -1.000000
7                H        -1.000000
8                I        -1.000000

In [46]:
df = pd.read_csv("../../output/conv/test_conv_level_conv.csv")

In [47]:
df[['conversation_num', 'team_burstiness']]

  conversation_num  team_burstiness
0                1              NaN
1                2             -1.0
2                3             -1.0
3                4             -1.0
4                5             -1.0
5                6             -1.0
6                A             -1.0