In [45]:
import pandas as pd
import numpy as np

In [46]:
def preprocess_conversation_columns(df):
	# remove all special characters from df
	df.columns = df.columns.str.replace('[^A-Za-z0-9_]', '', regex=True)
	
	# If data is grouped by batch/round, add a conversation num
	if {'batch_num', 'round_num'}.issubset(df.columns):
		df['conversation_num'] = df.groupby(['batch_num', 'round_num']).ngroup()
		df = df[df.columns.tolist()[-1:] + df.columns.tolist()[0:-1]] # make the new column first

	return(df)

In [47]:
test_dd = preprocess_conversation_columns(pd.read_csv('./data/raw_data/test_dd.csv'))
test_dd_vect = pd.read_csv('./embeddings/test_dd.csv')

In [48]:
csop = preprocess_conversation_columns(pd.read_csv('./data/raw_data/csopII_conversations_withblanks.csv'))
vect = pd.read_csv('./embeddings/csopII_conversations_withblanks.csv')

In [49]:
from features.get_all_DD_features import *

In [50]:
test_dd['message_embedding'] = conv_to_float_arr(test_dd_vect['message_embedding'].to_frame())
csop['message_embedding'] = conv_to_float_arr(vect['message_embedding'].to_frame())

In [56]:
# look at a unit case just for testing
csop = csop[csop["conversation_num"].isin(["25PJSrbtr8mkHTvcw_easy","cb2KMXFqSt2fJqRoa_hard"])]

In [7]:
get_DD(test_dd)

   conversation_num  discursive_diversity
0                 1          3.870704e-01
1                 2          8.280833e-01
2                 3         -2.220446e-16

In [57]:
get_DD(csop)

         conversation_num  discursive_diversity
0  25PJSrbtr8mkHTvcw_easy              0.726263
1  cb2KMXFqSt2fJqRoa_hard              0.630427

In [9]:
nanp = csop.loc[csop['conversation_num'] == '28LFTFoBTha9WeCxT_easy']
hi = np.mean(nanp['message_embedding'])
pairs = get_unique_pairwise_combos(hi)
np.nanmean(pairs)

0.0013878469461957733

In [31]:
csop.loc[csop['conversation_num'] == '25PJSrbtr8mkHTvcw_easy']

,conversation_num,batch_num,vis_img,int_verb,ort_img,rep_man,soc_pers,team_size,difficulty,score,duration,efficiency,speaker_nickname,message,timestamp,message_embedding
727,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,NiBqtamR7LYPByEoz,I think the next combination above 500 that wo...,2021-03-19T18:20:28.277Z,"[0.019077956676483154, -0.010986157692968845, ..."
728,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,NiBqtamR7LYPByEoz,I think 504 would still be ok?,2021-03-19T18:22:33.265Z,"[-0.025425974279642105, 0.08265340328216553, -..."
729,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,NiBqtamR7LYPByEoz,604-100,2021-03-19T18:22:41.278Z,"[-0.03982073813676834, 0.08185562491416931, -0..."
730,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,hF7iWkQvsomPnXY7S,sure,2021-03-19T18:22:50.937Z,"[-0.13950251042842865, -0.03979048505425453, -..."

In [11]:
test_dd_chunked = assign_chunk_nums(test_dd, 3)
test_dd_chunked

,conversation_num,speaker_nickname,timestamp,message,majority_pct,num_flipped,flipped_pct,num_votes,message_embedding,chunk_num
0,1,A,2020-04-20T18:27:20.125Z,"Hey, folks! What a sunny day, huh?",1,1,0.333333,3,"[-0.05474695563316345, 0.03426985442638397, 0....",0
1,1,B,2020-04-20T18:27:23.764Z,Totally! The weather's awesome. Perfect for a ...,1,1,0.333333,3,"[-0.07623177021741867, -0.03382902592420578, 0...",0
2,1,C,2020-04-20T18:27:27.724Z,Absolutely! The sun's warmth lifts my spirits....,1,1,0.333333,3,"[0.022043755277991295, 0.06103178858757019, 0....",0
3,1,A,2020-04-20T18:27:30.410Z,Your enthusiasm is contagious. We're like a sy...,1,1,0.333333,3,"[-0.00782862026244402, -0.12148767709732056, 0...",1
4,1,B,2020-04-20T18:27:35.506Z,"Exactly! Our thoughts harmonize effortlessly, ...",1,1,0.333333,3,"[0.026491936296224594, -0.0734446570277214, 0....",1
5,1,C,2020-04-20T18:28:09.451Z,"Well said! Our words sway together, a testamen...",1,1,0.333333,3,"[0.02942504733800888, 0.006728546228259802, 0....",1
6,1,A,2020-04-20T18:28:20.136Z,Your eloquence is inspiring! We're instruments...,1,1,0.333333,3,"[-0.0029373159632086754, -0.038919854909181595...",2
7,1,B,2020-04-20T18:28:20.136Z,Beautifully put! Our conversation is a masterp...,1,1,0.333333,3,"[-0.039978738874197006, 0.02529899962246418, 0...",2
8,2,A,2020-04-20T18:27:20.125Z,"Salutations, esteemed companions! Have you eve...",1,1,0.333333,3,"[-0.04252244532108307, -0.045107126235961914, ...",0
9,2,B,2020-04-20T18:27:23.764Z,"Yo, folks! Guess what? Last night's game was i...",1,1,0.333333,3,"[0.013962630182504654, 0.024840209633111954, 0...",0
10,2,C,2020-04-20T18:27:27.724Z,"Hey, everyone! Let's embark on a culinary adve...",1,1,0.333333,3,"[-0.024859678000211716, -0.09123209118843079, ...",0
11,2,A,2020-04-20T18:27:30.410Z,The wonders of quantum mechanics never cease t...,1,1,0.333333,3,"[-0.051735371351242065, -0.08504731953144073, ...",1
12,2,B,2020-04-20T18:27:35.506Z,"Dude, that game was off the charts! The team p...",1,1,0.333333,3,"[0.02194618619978428, 0.09317155927419662, 0.0...",1
13,2,C,2020-04-20T18:28:09.451Z,"Ah, the world of gastronomy! A realm where cul...",1,1,0.333333,3,"[0.008950394578278065, -0.016166768968105316, ...",1
14,2,A,2020-04-20T18:28:20.136Z,Quantum mechanics unravels the mysteries of th...,1,1,0.333333,3,"[-0.08999428898096085, 0.02500457689166069, -0...",2
15,2,B,2020-04-20T18:28:20.136Z,"Man, sports bring people together! The energy ...",1,1,0.333333,3,"[0.051622290164232254, 0.06192368268966675, 0....",2
16,3,A,2020-04-20T18:27:20.125Z,Hello! This is a test sentence in which we all...,1,1,0.333333,3,"[0.028341859579086304, 0.06234437972307205, 0....",0
17,3,B,2020-04-20T18:27:23.764Z,Hello! This is a test sentence in which we all...,1,1,0.333333,3,"[0.028341859579086304, 0.06234437972307205, 0....",0
18,3,C,2020-04-20T18:27:27.724Z,Hello! This is a test sentence in which we all...,1,1,0.333333,3,"[0.028341859579086304, 0.06234437972307205, 0....",0
19,3,A,2020-04-20T18:27:30.410Z,Hello! This is a test sentence in which we all...,1,1,0.333333,3,"[0.028341859579086304, 0.06234437972307205, 0....",1
20,3,B,2020-04-20T18:27:35.506Z,Hello! This is a test sentence in which we all...,1,1,0.333333,3,"[0.028341859579086304, 0.06234437972307205, 0....",1
21,3,C,2020-04-20T18:28:09.451Z,Hello! This is a test sentence in which we all...,1,1,0.333333,3,"[0.028341859579086304, 0.06234437972307205, 0....",1
22,3,A,2020-04-20T18:28:20.136Z,Hello! This is a test sentence in which we all...,1,1,0.333333,3,"[0.028341859579086304, 0.06234437972307205, 0....",2
23,3,B,2020-04-20T18:28:20.136Z,Hello! This is a test sentence in which we all...,1,1,0.333333,3,"[0.028341859579086304, 0.06234437972307205, 0....",2

In [61]:
csop_chunked = assign_chunk_nums(csop, 3)
csop_chunked

,conversation_num,batch_num,vis_img,int_verb,ort_img,rep_man,soc_pers,team_size,difficulty,score,duration,efficiency,speaker_nickname,message,timestamp,message_embedding,chunk_num
727,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,NiBqtamR7LYPByEoz,I think the next combination above 500 that wo...,2021-03-19T18:20:28.277Z,"[0.019077956676483154, -0.010986157692968845, ...",0
728,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,NiBqtamR7LYPByEoz,I think 504 would still be ok?,2021-03-19T18:22:33.265Z,"[-0.025425974279642105, 0.08265340328216553, -...",0
729,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,NiBqtamR7LYPByEoz,604-100,2021-03-19T18:22:41.278Z,"[-0.03982073813676834, 0.08185562491416931, -0...",1
730,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,hF7iWkQvsomPnXY7S,sure,2021-03-19T18:22:50.937Z,"[-0.13950251042842865, -0.03979048505425453, -...",1
2527,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,TtbAvteZKizwoyHeQ,827,2021-03-10T18:25:03.752Z,"[-0.05611119791865349, 0.055520616471767426, -...",0
2528,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,TtbAvteZKizwoyHeQ,894,2021-03-10T18:25:10.189Z,"[0.0008462711703032255, 0.06286414712667465, -...",0
2529,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,WiuwFxezEg3uSYY5J,Didn't we just have 899?,2021-03-10T18:25:18.538Z,"[-0.058363933116197586, 0.0004796952707692981,...",0
2530,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,ajAi4jxzqEwxpTvC4,we did until someone moved one,2021-03-10T18:25:31.682Z,"[0.052529413253068924, -0.050977353006601334, ...",0
2531,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,ajAi4jxzqEwxpTvC4,[ink you keep making our score worse,2021-03-10T18:26:52.241Z,"[-0.013198211789131165, 0.00264726928435266, 0...",0
2532,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,Q7Z4F3E6M2rPib8bp,916,2021-03-10T18:26:55.465Z,"[-0.03465019911527634, 0.0510905496776104, -0....",1
2533,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,WiuwFxezEg3uSYY5J,"Well done, Pink.",2021-03-10T18:26:58.017Z,"[-0.013680866919457912, 0.042766205966472626, ...",1
2534,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,WiuwFxezEg3uSYY5J,"It's OK, Turqoise. We have time to adjust.",2021-03-10T18:27:21.649Z,"[-0.009348239749670029, -0.043067533522844315,...",1
2535,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,ajAi4jxzqEwxpTvC4,I guess if you want to spend an hour for $6,2021-03-10T18:27:39.192Z,"[0.002892957767471671, -0.021120470017194748, ...",1
2536,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,TtbAvteZKizwoyHeQ,how many more rounds,2021-03-10T18:28:33.903Z,"[0.06289922446012497, 0.062271598726511, -0.05...",1
2537,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,WiuwFxezEg3uSYY5J,3?,2021-03-10T18:28:42.673Z,"[-0.034972529858350754, -0.09318390488624573, ...",2
2538,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,WiuwFxezEg3uSYY5J,"Honestly, I already forgot.",2021-03-10T18:29:03.537Z,"[-0.06569784134626389, -0.03449823334813118, 0...",2
2539,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,ajAi4jxzqEwxpTvC4,It can takeup to 60 minutes so I am assuming 10,2021-03-10T18:29:08.513Z,"[0.0014496613293886185, -0.008836911991238594,...",2
2540,cb2KMXFqSt2fJqRoa_hard,1,Low,Low,Low,Low,High,7,Hard [Corresponds to 'Super Hard' in PNAS],916.0,431.0,2.125290,TtbAvteZKizwoyHeQ,can all click satisfied so we can move to next...,2021-03-10T18:29:23.850Z,"[0.0018908712081611156, -0.04364408180117607, ...",2

In [62]:
conv = csop_chunked.loc[csop_chunked['conversation_num'] == '25PJSrbtr8mkHTvcw_easy']

In [63]:
saving = conv.groupby(['chunk_num'])['message_embedding'].apply(get_unique_pairwise_combos).reset_index()
# lst = saving['message_embedding'][0]
cos_dists_mean_widay_btwu = []

for lst in saving.message_embedding:

    # Make sure list isn't empty:
    if lst:
        # Store the cosine distances for the person's list of tuples
        cos_dists = []
        for tpl in lst:
            try:
                cos_d = 1 - get_cosine_similarity([tpl[0], tpl[1]])
                cos_dists.append(cos_d)
            except ValueError as e:
                # Occurs when np.nan in tuple
                pass

        # Compute mean of cos dists
        cos_dists_mean_widay_btwu.append(np.nanmean(cos_dists, dtype="float64"))
    else:
        cos_dists_mean_widay_btwu.append(np.nan)
cos_dists_mean_widay_btwu

[0.5788580914150436, 0.6963058408938405]

In [64]:
csop_chunked.loc[(csop_chunked['conversation_num'] == '25PJSrbtr8mkHTvcw_easy') & (csop_chunked['chunk_num'] == '0')]

,conversation_num,batch_num,vis_img,int_verb,ort_img,rep_man,soc_pers,team_size,difficulty,score,duration,efficiency,speaker_nickname,message,timestamp,message_embedding,chunk_num
727,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,NiBqtamR7LYPByEoz,I think the next combination above 500 that wo...,2021-03-19T18:20:28.277Z,"[0.019077956676483154, -0.010986157692968845, ...",0
728,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,NiBqtamR7LYPByEoz,I think 504 would still be ok?,2021-03-19T18:22:33.265Z,"[-0.025425974279642105, 0.08265340328216553, -...",0

In [38]:
csop_chunked.loc[(csop_chunked['conversation_num'] == '25PJSrbtr8mkHTvcw_easy') & (csop_chunked['chunk_num'] == '1')]

,conversation_num,batch_num,vis_img,int_verb,ort_img,rep_man,soc_pers,team_size,difficulty,score,duration,efficiency,speaker_nickname,message,timestamp,message_embedding,chunk_num
729,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,NiBqtamR7LYPByEoz,604-100,2021-03-19T18:22:41.278Z,"[-0.03982073813676834, 0.08185562491416931, -0...",1
730,25PJSrbtr8mkHTvcw_easy,1,Mixed,High,Low,High,Mixed,2,Easy [Corresponds to 'Hard' in PNAS],604.0,559.0,1.080501,hF7iWkQvsomPnXY7S,sure,2021-03-19T18:22:50.937Z,"[-0.13950251042842865, -0.03979048505425453, -...",1

In [39]:
csop_chunked.loc[(csop_chunked['conversation_num'] == '25PJSrbtr8mkHTvcw_easy') & (csop_chunked['chunk_num'] == '2')]

Empty DataFrame
Columns: [conversation_num, batch_num, vis_img, int_verb, ort_img, rep_man, soc_pers, team_size, difficulty, score, duration, efficiency, speaker_nickname, message, timestamp, message_embedding, chunk_num]
Index: []

In [40]:
csop_chunked.groupby(['conversation_num', 'chunk_num']).apply(get_DD)

                                          conversation_num
conversation_num       chunk_num
25PJSrbtr8mkHTvcw_easy 0         0  25PJSrbtr8mkHTvcw_easy  \
                       1         0  25PJSrbtr8mkHTvcw_easy

                                    discursive_diversity
conversation_num       chunk_num
25PJSrbtr8mkHTvcw_easy 0         0                   NaN
                       1         0              0.696306

In [41]:
print(csop_chunked.groupby(['conversation_num', 'chunk_num']).apply(get_DD).to_string())

                                          conversation_num  discursive_diversity
conversation_num       chunk_num
25PJSrbtr8mkHTvcw_easy 0         0  25PJSrbtr8mkHTvcw_easy                   NaN
                       1         0  25PJSrbtr8mkHTvcw_easy              0.696306

In [42]:
get_variance_in_DD(csop_chunked)

         conversation_num  variance_in_DD
0  25PJSrbtr8mkHTvcw_easy             NaN

In [65]:
# num_chunks = 3
# inter_chunk_range = [ [] for i in range(num_chunks - 1)]

# index = []
# for i in range(num_chunks - 1):
#     index.append("c" + str(i) + "_c" + str(i + 1))
# index
# pd.DataFrame(inter_chunk_range, index=index).T

get_within_person_disc_range(csop_chunked, num_chunks = 3)

### CURIOSITY - how did we get values for c1_c2 for `25PJSrbtr8mkHTvcw_easy`?
## There are only 2 chunks in this case...

[[0.6145188155861171, 0.8391692977533936, 0.7256118569586198, 0.8045276377162043, 0.9434096943299545, 0.9203022188120703], [0.8369321887883662, 0.8391692977533936, 0.7256118569586198, 0.6521813408319573, 0.7693649028182898, 0.7262687221547542]]
                           c0_c1     c1_c2
conversation_num
25PJSrbtr8mkHTvcw_easy  0.614519  0.836932
25PJSrbtr8mkHTvcw_easy  0.839169  0.839169
cb2KMXFqSt2fJqRoa_hard  0.725612  0.725612
cb2KMXFqSt2fJqRoa_hard  0.804528  0.652181
cb2KMXFqSt2fJqRoa_hard  0.943410  0.769365
cb2KMXFqSt2fJqRoa_hard  0.920302  0.726269

                        incongruent_modulation  within_person_disc_range
conversation_num
25PJSrbtr8mkHTvcw_easy                0.012618                  1.564895
cb2KMXFqSt2fJqRoa_hard                0.009574                  1.566820

In [19]:
get_within_person_disc_range(test_dd_chunked, num_chunks = 3)

[[0.8037338721586933, 0.8545239477097426, 0.7905633801890399, 0.3973550430249977, 0.3870970209021124, 0.40296760824260613, -2.220446049250313e-16, -2.220446049250313e-16, -2.220446049250313e-16], [0.554592139634682, 0.5210188197799636, 0.951488253423191, 0.3167915107063928, 0.3579536427190626, 0.9616013000252147, -2.220446049250313e-16, -2.220446049250313e-16, 0.8783546762031388]]
                         c0_c1         c1_c2
conversation_num
1                 8.037339e-01  5.545921e-01
1                 8.545239e-01  5.210188e-01
1                 7.905634e-01  9.514883e-01
2                 3.973550e-01  3.167915e-01
2                 3.870970e-01  3.579536e-01
2                 4.029676e-01  9.616013e-01
3                -2.220446e-16 -2.220446e-16
3                -2.220446e-16 -2.220446e-16
3                -2.220446e-16  8.783547e-01

                  incongruent_modulation  within_person_disc_range
conversation_num
1                               0.038978                  1.491973
2                               0.086917                  0.941255
3                               0.171446                  0.292785