# Imports

In [1]:
import pandas as pd
from feature_builder import FeatureBuilder

# Initialization

In [2]:
feature_builder = FeatureBuilder(
    input_file_path = "data/raw_data/juries_tiny_for_testing.csv", 
    output_file_path_chat_level = "output/jury_TINY_output_chat_level.csv", 
    output_file_path_conv_level = "output/jury_TINY_output_conversation_level.csv" 
)

In [3]:
print(feature_builder.chat_data.shape)
feature_builder.chat_data.head()

(97, 10)

,batch_num,round_num,speaker_hash,speaker_nickname,timestamp,message,majority_pct,num_flipped,flipped_pct,num_votes
0,0,0,5e7e1e0031f4e454e196c30b,niceRhino,2020-04-20T18:27:20.125Z,Hello!,1.0,1,0.333333,3
1,0,0,5e31d6e4e31c5304c46f1413,culturedCow,2020-04-20T18:27:23.764Z,Hi!,1.0,1,0.333333,3
2,0,0,5e7e4f4c31f4e454e196c9c4,spryBison,2020-04-20T18:27:27.724Z,Hello,1.0,1,0.333333,3
3,0,0,5d482ea421c9be351f762255,youngLion,2020-04-20T18:27:30.410Z,Hi,1.0,1,0.333333,3
4,0,0,5e84cc3c50f6e364321d6265,smallGiraffe,2020-04-20T18:27:35.506Z,hi,1.0,1,0.333333,3

In [4]:
print(feature_builder.conv_data.shape)
feature_builder.conv_data.head()

(2, 2)

   batch_num  round_num
0          0          0
1          0          2

# Feature Building Pipeline

In [5]:
feature_builder.featurize(col="message")

In [6]:
print(feature_builder.chat_data.shape)
feature_builder.chat_data.head()

(97, 67)

,batch_num,round_num,speaker_hash,speaker_nickname,timestamp,message,majority_pct,num_flipped,flipped_pct,num_votes,...,verbs,friends,article,argue,auxiliary_verbs,cognitive_mech,preposition,first_person_plural,percept,second_person
0,0,0,5e7e1e0031f4e454e196c30b,niceRhino,2020-04-20T18:27:20.125Z,hello,1.0,1,0.333333,3,...,0,0,0,0,0,0,0,0,0,0
1,0,0,5e31d6e4e31c5304c46f1413,culturedCow,2020-04-20T18:27:23.764Z,hi,1.0,1,0.333333,3,...,0,0,0,0,0,0,0,0,0,0
2,0,0,5e7e4f4c31f4e454e196c9c4,spryBison,2020-04-20T18:27:27.724Z,hello,1.0,1,0.333333,3,...,0,0,0,0,0,0,0,0,0,0
3,0,0,5d482ea421c9be351f762255,youngLion,2020-04-20T18:27:30.410Z,hi,1.0,1,0.333333,3,...,0,0,0,0,0,0,0,0,0,0
4,0,0,5e84cc3c50f6e364321d6265,smallGiraffe,2020-04-20T18:27:35.506Z,hi,1.0,1,0.333333,3,...,0,0,0,0,0,0,0,0,0,0

In [7]:
print(feature_builder.conv_data.shape)
feature_builder.conv_data.head()

(2, 12)

,batch_num,round_num,gini_coefficient_num_words,gini_coefficient_num_chars,average_message_count,std_message_count,average_word_count,std_word_count,max_messages,min_messages,max_words,min_words
0,0,0,0.159463,0.166055,6.5,2.397916,107.000000,33.948490,9,1,140,30
1,0,2,0.125695,0.124663,7.5,3.685557,109.833333,28.457083,12,3,169,76